# Generated by Django 3.0.1 on 2020-01-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
